2023-06-18 18:17:34,537 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:32]
2023-06-18 18:45:23,860 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:32]
2023-06-18 18:45:28,960 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:32]
2023-06-18 18:53:56,422 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:32]
2023-06-18 18:54:35,391 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:32]
2023-06-18 19:00:14,583 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:32]
2023-06-18 20:27:04,179 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:32]
2023-06-18 20:33:26,317 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:32]
2023-06-18 21:08:44,287 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:34]
2023-06-19 14:12:01,592 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:34]
2023-06-19 14:12:06,976 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:34]
2023-06-19 14:12:24,854 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:34]
2023-06-19 14:13:58,852 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:34]
2023-06-19 14:14:52,310 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:34]
2023-06-19 15:36:16,487 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:34]
2023-06-19 16:27:32,795 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:36]
2023-06-19 22:07:27,140 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:72]
2023-06-19 22:07:31,977 ERROR: Exception on /index [GET] [in /Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/weixia/Documents/repo/microblog/app/main/routes.py", line 28, in index
    return render_template('index.html', title='Home', form=form,
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/weixia/Documents/repo/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/weixia/Documents/repo/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/Users/weixia/Documents/repo/microblog/app/templates/base.html", line 17, in block 'navbar'
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2023-06-19 22:07:46,462 ERROR: Exception on /index [GET] [in /Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/weixia/Documents/repo/microblog/app/main/routes.py", line 28, in index
    return render_template('index.html', title='Home', form=form,
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/weixia/Documents/repo/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/weixia/Documents/repo/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/Users/weixia/Documents/repo/microblog/app/templates/base.html", line 17, in block 'navbar'
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2023-06-19 22:12:02,050 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:72]
